
  Performance statistics for DSP solver: icalls =      0

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           11586
     no. of nonzeroes in lower triangle of a =          626325
     no. of nonzeroes in the factor l        =         4230487
     ratio of nonzeroes in factor (min/max)  =          0.8272
     number of super nodes                   =             263
     maximum order of a front matrix         =            1038
     maximum size of a front matrix          =          539241
     maximum size of a front trapezoid       =          324447
     ParMETIS reordering method used (speed) 
     no. of floating point ops for factor    =      1.8528D+09
     no. of floating point ops for solve     =      1.6085D+07
     ratio of flops for factor (min/max)     =          0.8410
     ratio of allocated memory (max/min)     =          1.0000
     number of positive pivots               =               0
     number of negative pivots               =               1
     number of near-zero pivots              =               0
     partial pivoting tolerance used         =      2.9644-323
     number of 1x1 pivots                    =           11586
     number of 2x2 pivots                    =               0
     number of delayed pivots                =               0
     number of deferred pivots               =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.078125
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.000000
     time (cpu & wall) for matrix distrib.   =        0.000000        0.015625
     time (cpu & wall) for numeric factor    =        0.000000        0.031250
     computational rate (gflops) for factor  =        Infinity       59.289885

     no input or output performed

  Solver Memory allocated on core    0       =        0.000 MB
  Solver Memory allocated on core    1       =        0.000 MB
  Solver Memory allocated on core    2       =        0.000 MB
  Solver Memory allocated on core    3       =        0.000 MB
  Total Solver Memory allocated by all cores =        0.000 MB

